# This Playbook to configure Apache server
# TEST
- hosts: all
  become: yes
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Start httpd
    service:
     name: httpd
     state: started
     enabled: yes

  - name: Allow on FW
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled

  - name: Edit doc page
    lineinfile:
      path: /var/www/html/index.html
      line: “This is from my Playbook”
      create: yes
    tags: http

  - name: Test the web
    shell: curl localhost
    tags: http
