- name: Create mount
  file:
    path: "{{ client }}"
    state: directory
  tags: client:

- name: mount to NFS
  mount:
    src: '{{ n3 }}:{{ nfss }}'
    path: "{{ client }}"
    state: mounted
    fstype: nfs
  tags: client
