---
# tasks file for verizon-project
#
- name: Include Mount.yml tasks
  import_tasks: mount.yml
  when: ansible_nodename == 'node3'

- name: Include nfsserver.yml tasks
  import_tasks: nfsserver.yml
  when: ansible_nodename == 'node3'

- name: Include client.yml tasks
  import_tasks: client.yml
  when: ansible_nodename == 'node1' or ansible_nodename == 'node2'
  tags: client
